version: '3.5'

services:
  postgres-server:
    image: postgres:16
    container_name: zabbix-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    volumes:
      - /opt/docker/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    depends_on:
      - postgres-server
    ports:
      - "10051:10051"
    volumes:
      - /opt/docker/zbx-db-backup:/var/lib/zabbix/backups
    restart: always
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    restart: always
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: docker_zabbix_agent
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-server
    restart: always
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker/pgdata

  zbx-db-backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker/zbx-db-backup
